# Generated by Django 4.1.2 on 2022-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='descripcion',
            field=models.TextField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
