# Generated by Django 4.1.2 on 2022-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_animal_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animal'),
        ),
    ]
