# Generated by Django 4.1.2 on 2023-06-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_animal_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
